#! /bin/bash
hostname=`hostname`
sed -r '/^\#/d' /etc/hosts > /etc/temp_hosts
prefix=`cat /etc/temp_hosts | grep $hostname | cut -d ' ' -f 1 | cut -d '.' -f 1-3`
hostlist=`cat /etc/temp_hosts | grep $prefix | awk '{print $2}'`
rm -rf /etc/temp_hosts

function usage() 
{
  echo "Help(-h|--help) for icfs-object-config"
  echo "Usage:"
  echo "  Options:"
  echo "  install            :install rgw config"
  echo "  uninstall          :uninstall rgw config"
  echo ""
  echo "Function"
  echo "install rgw config"
  echo "    >>icfs-object-config install<<"
  echo "uninstall rgw config"
  echo "    >>icfs-object-config uninstall<<"
  echo ""
  echo "Exit status:"
  echo "0 if executed successfully"
  echo "1 if executed unsuccessfully"
}

if [ $# -ne 1 ]
then
  usage
  exit 1
fi

if [ $1 == "-h" -o $1 == "--help" ]
then
  usage
  exit 0
fi


for host in $hostlist
do
  ret=`ssh $host "icfs-object-install --$1 --client radosgw.gateway --port 8009"`
  ok=$? 
done

if [ $ok -eq 0 ]
then
  echo $ret
  exit 0
else
  echo $ret
  exit 1
fi

